# ===========================================
# DFormer 模型配置文件
# ===========================================

version: v1                    # v1 (DFormer) 或 v2 (DFormerv2)
model_type: base               # tiny, small, base, large

# 相对于项目根目录的路径
checkpoint_path: model_weights/dformer/NYUv2_DFormer_Base.pth
log_path : ./logs

num_classes: 40                # NYUv2: 40 类
decoder: ham                   # ham, MLPDecoder
decoder_embed_dim: 512

device: cuda
freeze: true                   # 是否冻结参数

epochs: 1000
batch_size : 8 
pad : 30
learning_rate : 2.5

momentum: 0.9
weight_decay: 0.0
warmup_steps: 1000


# ---------- 数据集 (供参考) ----------
# dataset:
#   name: NYUDepthv2
#   root: datasets/NYUDepthv2
#   image_height: 480
#   image_width: 640
#   num_classes: 40